name: Deploy static/published ASP.NET site to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bgpl-frontend-graphics'   # your app service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .

